In [2]:
import pandas as pd
import numpy as np
import os

In [6]:
base_path = "C:\\Users\\wenyang.zhang\\Documents\\MySpace\\Workspace\\PredictionPlatform\\Datasource"
file_path = os.path.join(base_path, "BANNER_0.csv")
df = pd.read_csv(file_path)

In [52]:
df.head(20)
# df["REPORT_DATE"].unique()

,REPORT_DATE,STORE_BKEY,BANNER_NAME,STORE_TYPE,PRODUCT_BKEY,BRAND_NAME,AMOUNT_PER_KG,PRICE_PER_KG,HAS_GROUND,WEEK_OF_YEAR,...,IS_NEWYEAR,IS_CHRISTMAS,IS_12,IS_11,IS_618,IS_SUMMER,IS_WINTER,STORE_COUNT,CITY_COUNT,RN
0,2018-02-24,BJ07110011,7-Eleven,CVS,XCN0401200,ROCHER,20.295983,162.367865,0,8,...,0,0,0,0,0,0,1,1497,12,1
1,2018-02-24,BJ07110011,7-Eleven,CVS,XCN04O2904,ROCHER,4.761905,178.666667,0,8,...,0,0,0,0,0,0,1,1497,12,1
2,2018-02-24,BJ07110011,7-Eleven,CVS,XCN1107500,KINDER CHOCOLATE,8.510638,100.765957,0,8,...,0,0,0,0,0,0,1,1497,12,1
3,2018-02-24,BJ07110011,7-Eleven,CVS,XCN1501100,RAFFAELLO,20.382166,138.598726,0,8,...,0,0,0,0,0,0,1,1497,12,1
4,2018-02-24,BJ07110011,7-Eleven,CVS,XCN8701862,KINDER JOY,0.000000,0.000000,0,8,...,0,0,0,0,0,0,1,1497,12,1
5,2018-02-24,BJ07110011,7-Eleven,CVS,XCN8701863,KINDER JOY,7.111111,144.497778,0,8,...,0,0,0,0,0,0,1,1497,12,1
6,2018-02-24,BJ07110011,7-Eleven,CVS,XCN87O8063,KINDER JOY,20.869565,151.930435,0,8,...,0,0,0,0,0,0,1,1497,12,1
7,2018-02-24,BJ07110011,7-Eleven,CVS,XCNC911600,COLLECTION,2.702703,172.756757,0,8,...,0,0,0,0,0,0,1,1497,12,1
8,2018-02-24,BJ07110012,7-Eleven,CVS,XCN0401200,ROCHER,20.295983,162.367865,0,8,...,0,0,0,0,0,0,1,1497,12,1
9,2018-02-24,BJ07110012,7-Eleven,CVS,XCN04O2904,ROCHER,4.761905,178.666667,0,8,...,0,0,0,0,0,0,1,1497,12,1
10,2018-02-24,BJ07110012,7-Eleven,CVS,XCN1107500,KINDER CHOCOLATE,8.510638,100.765957,0,8,...,0,0,0,0,0,0,1,1497,12,1
11,2018-02-24,BJ07110012,7-Eleven,CVS,XCN1501100,RAFFAELLO,20.382166,138.598726,0,8,...,0,0,0,0,0,0,1,1497,12,1
12,2018-02-24,BJ07110012,7-Eleven,CVS,XCN8701862,KINDER JOY,0.000000,0.000000,0,8,...,0,0,0,0,0,0,1,1497,12,1
13,2018-02-24,BJ07110012,7-Eleven,CVS,XCN8701863,KINDER JOY,7.111111,144.497778,0,8,...,0,0,0,0,0,0,1,1497,12,1
14,2018-02-24,BJ07110012,7-Eleven,CVS,XCN87O8063,KINDER JOY,20.869565,151.930435,0,8,...,0,0,0,0,0,0,1,1497,12,1
15,2018-02-24,BJ07110012,7-Eleven,CVS,XCNC911600,COLLECTION,2.702703,172.756757,0,8,...,0,0,0,0,0,0,1,1497,12,1
16,2018-02-24,BJ07110013,7-Eleven,CVS,XCN0401200,ROCHER,20.295983,162.367865,0,8,...,0,0,0,0,0,0,1,1497,12,1
17,2018-02-24,BJ07110013,7-Eleven,CVS,XCN04O2904,ROCHER,4.761905,178.666667,0,8,...,0,0,0,0,0,0,1,1497,12,1
18,2018-02-24,BJ07110013,7-Eleven,CVS,XCN1107500,KINDER CHOCOLATE,8.510638,100.765957,0,8,...,0,0,0,0,0,0,1,1497,12,1
19,2018-02-24,BJ07110013,7-Eleven,CVS,XCN1501100,RAFFAELLO,20.382166,138.598726,0,8,...,0,0,0,0,0,0,1,1497,12,1

In [12]:
df_head.stack()

0  REPORT_DATE       2018-02-24
   STORE_BKEY        BJ07110011
   BANNER_NAME         7-Eleven
   STORE_TYPE               CVS
   PRODUCT_BKEY      XCN0401200
   BRAND_NAME            ROCHER
   AMOUNT_PER_KG         20.296
   PRICE_PER_KG         162.368
   HAS_GROUND                 0
   WEEK_OF_YEAR               8
   MONTH_OF_YEAR              2
   YEAR_OF_WEEK            2018
   IS_VALENTINE               0
   IS_TEACHER                 0
   IS_C_VALENTINE             0
   IS_CHILDREN                0
   IS_NEWYEAR                 0
   IS_CHRISTMAS               0
   IS_12                      0
   IS_11                      0
   IS_618                     0
   IS_SUMMER                  0
   IS_WINTER                  1
   STORE_COUNT             1497
   CITY_COUNT                12
   RN                         1
1  REPORT_DATE       2018-02-24
   STORE_BKEY        BJ07110011
   BANNER_NAME         7-Eleven
   STORE_TYPE               CVS
                        ...
3  IS_WINTER                  1
   STORE_COUNT             1497
   CITY_COUNT                12
   RN                         1
4  REPORT_DATE       2018-02-24
   STORE_BKEY        BJ07110011
   BANNER_NAME         7-Eleven
   STORE_TYPE               CVS
   PRODUCT_BKEY      XCN8701862
   BRAND_NAME        KINDER JOY
   AMOUNT_PER_KG              0
   PRICE_PER_KG               0
   HAS_GROUND                 0
   WEEK_OF_YEAR               8
   MONTH_OF_YEAR              2
   YEAR_OF_WEEK            2018
   IS_VALENTINE               0
   IS_TEACHER                 0
   IS_C_VALENTINE             0
   IS_CHILDREN                0
   IS_NEWYEAR                 0
   IS_CHRISTMAS               0
   IS_12                      0
   IS_11                      0
   IS_618                     0
   IS_SUMMER                  0
   IS_WINTER                  1
   STORE_COUNT             1497
   CITY_COUNT                12
   RN                         1
Length: 130, dtype: object

In [44]:
df_trend =

KeyboardInterrupt:

In [53]:
filePaht = os.path.join(base_path, "BANNER.csv")
reader = pd.read_csv(filePaht, iterator=True, chunksize=5)
reader.get_chunk()

,REPORT_DATE,STORE_BKEY,BANNER_NAME,STORE_TYPE,PRODUCT_BKEY,BRAND_NAME,AMOUNT_PER_KG,PRICE_PER_KG,HAS_GROUND,WEEK_OF_YEAR,...,IS_NEWYEAR,IS_CHRISTMAS,IS_12,IS_11,IS_618,IS_SUMMER,IS_WINTER,STORE_COUNT,CITY_COUNT,RN
0,2018-02-24,BJ07110011,7-Eleven,CVS,XCN0401200,ROCHER,20.295983,162.367865,0,8,...,0,0,0,0,0,0,1,1497,12,1
1,2018-02-24,BJ07110011,7-Eleven,CVS,XCN04O2904,ROCHER,4.761905,178.666667,0,8,...,0,0,0,0,0,0,1,1497,12,1
2,2018-02-24,BJ07110011,7-Eleven,CVS,XCN1107500,KINDER CHOCOLATE,8.510638,100.765957,0,8,...,0,0,0,0,0,0,1,1497,12,1
3,2018-02-24,BJ07110011,7-Eleven,CVS,XCN1501100,RAFFAELLO,20.382166,138.598726,0,8,...,0,0,0,0,0,0,1,1497,12,1
4,2018-02-24,BJ07110011,7-Eleven,CVS,XCN8701862,KINDER JOY,0.000000,0.000000,0,8,...,0,0,0,0,0,0,1,1497,12,1

In [54]:
reader.get_chunk()

,REPORT_DATE,STORE_BKEY,BANNER_NAME,STORE_TYPE,PRODUCT_BKEY,BRAND_NAME,AMOUNT_PER_KG,PRICE_PER_KG,HAS_GROUND,WEEK_OF_YEAR,...,IS_NEWYEAR,IS_CHRISTMAS,IS_12,IS_11,IS_618,IS_SUMMER,IS_WINTER,STORE_COUNT,CITY_COUNT,RN
5,2018-02-24,BJ07110011,7-Eleven,CVS,XCN8701863,KINDER JOY,7.111111,144.497778,0,8,...,0,0,0,0,0,0,1,1497,12,1
6,2018-02-24,BJ07110011,7-Eleven,CVS,XCN87O8063,KINDER JOY,20.869565,151.930435,0,8,...,0,0,0,0,0,0,1,1497,12,1
7,2018-02-24,BJ07110011,7-Eleven,CVS,XCNC911600,COLLECTION,2.702703,172.756757,0,8,...,0,0,0,0,0,0,1,1497,12,1
8,2018-02-24,BJ07110012,7-Eleven,CVS,XCN0401200,ROCHER,20.295983,162.367865,0,8,...,0,0,0,0,0,0,1,1497,12,1
9,2018-02-24,BJ07110012,7-Eleven,CVS,XCN04O2904,ROCHER,4.761905,178.666667,0,8,...,0,0,0,0,0,0,1,1497,12,1

In [55]:
reader.get_chunk()

,REPORT_DATE,STORE_BKEY,BANNER_NAME,STORE_TYPE,PRODUCT_BKEY,BRAND_NAME,AMOUNT_PER_KG,PRICE_PER_KG,HAS_GROUND,WEEK_OF_YEAR,...,IS_NEWYEAR,IS_CHRISTMAS,IS_12,IS_11,IS_618,IS_SUMMER,IS_WINTER,STORE_COUNT,CITY_COUNT,RN
10,2018-02-24,BJ07110012,7-Eleven,CVS,XCN1107500,KINDER CHOCOLATE,8.510638,100.765957,0,8,...,0,0,0,0,0,0,1,1497,12,1
11,2018-02-24,BJ07110012,7-Eleven,CVS,XCN1501100,RAFFAELLO,20.382166,138.598726,0,8,...,0,0,0,0,0,0,1,1497,12,1
12,2018-02-24,BJ07110012,7-Eleven,CVS,XCN8701862,KINDER JOY,0.000000,0.000000,0,8,...,0,0,0,0,0,0,1,1497,12,1
13,2018-02-24,BJ07110012,7-Eleven,CVS,XCN8701863,KINDER JOY,7.111111,144.497778,0,8,...,0,0,0,0,0,0,1,1497,12,1
14,2018-02-24,BJ07110012,7-Eleven,CVS,XCN87O8063,KINDER JOY,20.869565,151.930435,0,8,...,0,0,0,0,0,0,1,1497,12,1

In [64]:
reader.get_chunk()

,REPORT_DATE,STORE_BKEY,BANNER_NAME,STORE_TYPE,PRODUCT_BKEY,BRAND_NAME,AMOUNT_PER_KG,PRICE_PER_KG,HAS_GROUND,WEEK_OF_YEAR,...,IS_NEWYEAR,IS_CHRISTMAS,IS_12,IS_11,IS_618,IS_SUMMER,IS_WINTER,STORE_COUNT,CITY_COUNT,RN
55,2018-02-24,BJ07110019,7-Eleven,CVS,XCNC911600,COLLECTION,2.702703,172.756757,0,8,...,0,0,0,0,0,0,1,1497,12,1
56,2018-02-24,BJ07110020,7-Eleven,CVS,XCN0401200,ROCHER,20.295983,162.367865,0,8,...,0,0,0,0,0,0,1,1497,12,1
57,2018-02-24,BJ07110020,7-Eleven,CVS,XCN04O2904,ROCHER,4.761905,178.666667,0,8,...,0,0,0,0,0,0,1,1497,12,1
58,2018-02-24,BJ07110020,7-Eleven,CVS,XCN1107500,KINDER CHOCOLATE,8.510638,100.765957,0,8,...,0,0,0,0,0,0,1,1497,12,1
59,2018-02-24,BJ07110020,7-Eleven,CVS,XCN1501100,RAFFAELLO,20.382166,138.598726,0,8,...,0,0,0,0,0,0,1,1497,12,1

In [18]:
filePaht = os.path.join(base_path, "BANNER_00.csv")
reader = pd.read_csv(filePaht, iterator=True, chunksize=10)
reader.get_chunk()
reader.empty

AttributeError: 'TextFileReader' object has no attribute 'empty'

In [8]:
reader.get_chunk()

   REPORT_DATE\tSTORE_BKEY\tBANNER_NAME\tSTORE_TYPE\tPRODUCT_BKEY\tBRAND_NAME\tAMOUNT_PER_KG\tPRICE_PER_KG\tHAS_GROUND\tWEEK_OF_YEAR\tMONTH_OF_YEAR\tYEAR_OF_WEEK\tIS_VALENTINE\tIS_TEACHER\tIS_C_VALENTINE\tIS_CHILDREN\tIS_NEWYEAR\tIS_CHRISTMAS\tIS_12\tIS_11\tIS_618\tIS_SUMMER\tIS_WINTER\tSTORE_COUNT\tCITY_COUNT\tRN
10  2018/2/24\tBJ07110012\t7-Eleven\tCVS\tXCN11075...
11  2018/2/24\tBJ07110012\t7-Eleven\tCVS\tXCN15011...

In [17]:
reader.get_chunk()

StopIteration: